/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Aula1;

import ws3dproxy.CommandExecException;
import ws3dproxy.WS3DProxy;
import ws3dproxy.model.Creature;
import ws3dproxy.model.World;
import ws3dproxy.model.WorldPoint;
import ws3dproxy.util.Constants;

public class App {
    public App(){
        WS3DProxy proxy = new WS3DProxy();
        UI ui = new UI();
try {   
     World w = World.getInstance();
     w.reset();
     World.createFood(0, 350, 75);
     World.createFood(0, 100, 220);
     World.createFood(0, 250, 210);
     Creature c = proxy.createCreature(100,450,0);
     c.start();
     WorldPoint position = c.getPosition();
     double pitch = c.getPitch();
     double fuel = c.getFuel();
     while(true){
         if(ui.checkCanStep()){
              c.moveto(Constants.DEFAULT_CREATURE_SPEED/4,ui.getMovementDirections()[0], ui.getMovementDirections()[1]);
             
              
         }
         else{
         c.moveto(0,ui.getMovementDirections()[0], ui.getMovementDirections()[1]);
         
         }
     }
    
    
    } catch (CommandExecException e) {
     System.out.println("Erro capturado"); 
    }
    }
    

    public static void main(String[] args) {
       App app = new App();
    }
}
